# neon green synthwave kitty
include theme.conf

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
font_size        11.0

# translucent blurred terminal (blur handled by Hyprland for kitty windows)
background_opacity 0.85
dynamic_background_opacity yes
confirm_os_window_close 0

window_padding_width 10
hide_window_decorations yes
cursor_trail 6
cursor_trail_decay 0.05 0.3
cursor_beam_thickness 2.2
window_border_width 1.5pt

scrollback_lines 10000
enable_audio_bell no
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_activity_symbol "●"
bell_on_tab yes
