#!/usr/bin/env bash
# random cool quote for waybar
quotes=(
"the quieter you become, the more you can hear"
"talk is cheap. show me the code."
"there is no patch for human stupidity"
"stay hungry, stay foolish"
"first, solve the problem. then, write the code."
"the cloud is just someone else's computer"
"it works on my machine"
"rm -rf doubt"
"green is the new black"
"hack the planet"
"chmod +x yourself"
"i use hyprland btw"
"reality is just a shared hallucination"
"the night is dark and full of terminals"
"sudo make me a sandwich"
"keep calm and kill -9"
"there are 10 types of people in this world"
"segmentation fault (core dumped) — but make it cute"
"may your compiles be swift and your bugs be shallow"
"wake up, samurai. we have a kernel to panic."
"trust the process, fork the rest"
"i'd tell you a UDP joke but you might not get it"
"entropy always wins"
"be the daemon you wish to see in the world"
)
echo "  ${quotes[$RANDOM % ${#quotes[@]}]}"
